### PR TITLE
Added: build_ebook_v2.py

### PR DESCRIPTION
**Pull request by H-G-Hristov**
- Added `build_ebook_v2.py` script which adjusts the headings based on the directory structure to create a `Markdown` document, which enables proper TOC (Table of Contents) generation (matching the one the website) by `pandoc`.
- Also added the generated PDF and ePub books as a proof.

Notes: The new script is based on the old one. It uses the same RegEx'es unchanged. It's a bit verbose to make it more clear what's going on.

(I used the email of my other account so I didn't expect that GitHub will link the commits in such way.)

### CODE REVIEW

**Comment by Overv** [comment]
Thank you for your PR. Could you change the PR to overwrite the original script rather than adding a new file? That would make it more clear that it is intended to be replaced. Also, could you generate the French documents and add them to the PR as well?

**Comment by H-G-Hristov** [comment]
@Overv Thank you for the remarks.
1. Fixed the title page/meta data
2. Replaced the old script
3. Generated new ebooks for English and French

**Comment by Overv** [comment]
I'm sorry for not having gotten back to you yet. I'll try to review this as soon as possible, which will probably be tomorrow.

**Comment by Overv** [comment]
I refactored the script to be more maintainable and fit my own preferred code style better, and merged it. Thank you for your contribution.

**Pull request merged**
