### PR TITLE
Use C++11 in-class initialization in VDeleter

### PR DESCRIPTION
**Pull request by GuildMasterInfinite**
Since these tutorials are for C++11, I would like to suggest a change to improve the code.

The VDeleter class template has 3 constructors (for different kinds of objects), and they all have the same first line:
```
object = VK_NULL_HANDLE;
```

This change skips copying the same line 3 times, by moving everything to one line.
```
T object{ VK_NULL_HANDLE };
```
For more info: http://en.cppreference.com/w/cpp/language/data_members#Member_initialization

### CODE REVIEW

**Comment by Overv** [comment]
That is a good idea. Any reason for choosing an initializer over assignment?

**Comment by GuildMasterInfinite** [comment]
Besides being shorter, initialization also avoids doing something twice.
In those constructors, right before the `object = VK_NULL_HANDLE` line, the compiler will first default-initialize the member variables. According to cppreference.com:

> Before the compound statement that forms the function body of the constructor begins executing, initialization of all direct bases, virtual bases, and non-static data members is finished.

So the compiler does something like this behind the scenes:
`VDeleter(...) : object( ), deleter( )`
which means object will be NULL / nullptr / 0, aka VK_NULL_HANDLE, and deleter will be nullptr. They are initialized twice.

Afterwards, we set them to `VK_NULL_HANDLE` again, or we set the deleter function to a lambda.

In theory, an optimizing compiler will just drop the `object = VK_NULL_HANDLE` lines and directly replace them with the lines suggested above, since there is no change to the object from the constructor call till the assignment.

**Comment by Overv** [comment]
I've made the change.

**Comment by GuildMasterInfinite** [comment]
Thanks!

**Pull request closed without merging**
