### PR TITLE
Added shaders for drawing a triangle

### PR DESCRIPTION
**Pull request by vityafx**
Currently there is no way to compile a code used in "Drawing a triangle" tutorial without creating shaders. I have added shaders to make it possible.

### CODE REVIEW

**Comment by Overv** [comment]
The shader code is already listed in the *Shader Modules* chapter.

**Comment by vityafx** [comment]
Yes, it is listed but it is not included in the git repository. So, just to check you installed vulkan correctly and everything works fine on your system and you able to learn vulkan with your website (vulkan-tutorial.com) you need only to compile the code and run it if you merge the PR. Otherwise you need to read everything and just find out something is wrong. Personally, I think it is better to run the example code to see everything is okay BEFORE reading the tutorial part. Also I read the example code on one monitor and tutorial on another which makes understanding easier.

**Comment by Overv** [comment]
The *Development environment* chapter already includes all the instructions and code you need to check if Vulkan is working. If the samples in there are working, then you will not run into any surprises during the main tutorials.

You have misunderstood the purpose of the example code. The example code is there for if you get stuck somewhere in the tutorial, for example if you are unsure how to organise a function. It is not there for people who just want to run Vulkan demos. That's what [these demos](https://github.com/SaschaWillems/Vulkan) are for.

**Comment by Overv** [comment]
Shaders have been included now.

**Pull request closed without merging**
