### PR TITLE
Fix else branch of chooseSwapExtent for HDPI/retina displays

### PR DESCRIPTION
**Pull request by maltekliemann**
When using an HDPI display, using the window size `{WIDTH, HEIGHT}` to determine swapchain image size is incorrect. See the following links:

* https://www.glfw.org/docs/latest/window.html#window_size
* https://www.glfw.org/docs/latest/window.html#window_fbsize
* https://www.glfw.org/faq.html#43---why-is-my-output-in-the-lower-left-corner-of-the-window

Short version: The window size in GLFW is specified in screen coordinates, but Vulkan requires the swapchain image extent to be specified in pixel. On HDPI displays, these are not the same thing.

Instead, the framebuffer size is now used to determine the swapchain extent. Using the implementation of `chooseSwapExtent` from `16_swap_chain_recreation.cpp` seemed appropriate. Beyond "Swap chain recreation" no changes are necessary.

I'm a little bit suprised that this hasn't been an issue for anyone. I'm using macOS, and my app doesn't enter the `else` branch, so I don't experience any problems either (Vulkan automatically suggests doubled width and height). The specification doesn't seem to say _when_ `width == UINT32_MAX` occurs.

### CODE REVIEW

**Comment by maltekliemann** [comment]
The tutorial is now changed accordingly. I've tried to keep the explanation of the problem as short as possible. I don't know if there is a more elegant solution for this problem. `glfwGetFramebufferSize` is now shoved in a bit awkwardly, instead of being introduced naturally during _Swap chain recreation_.

When I write "GLFW uses two units when measuring sizes: pixels and screen coordinates [...]", that's a bit of a lie. There are other measurements, but these are the two that count.

**Comment by Overv** [comment]
Could you elaborate on the changes besides glfwGetFramebufferSize?

**Comment by maltekliemann** [comment]
My bad, I was careless when I pushed that. Sorry! :(

I've amended the commit. It should only contain changes relevant to swapchain extent.

**Comment by Overv** [comment]
Apologies for not getting back to this sooner, thanks for the work! :+1:

**Comment by maltekliemann** [comment]
Not to worry! Thanks for the tutorial! :)

**Pull request merged**
