### PR TITLE
Chinese 01

### PR DESCRIPTION
**Pull request by huzhenbang**

### CODE REVIEW

**Comment by Overv** [comment]
Awesome, thanks for doing this!

I'd say that the first translated pages can be published once at least "Drawing a triangle" has been fully translated. I'll hold off on reviewing & merging until then.

Are there any other native speakers who would have time in the future to review the translation when it gets to that point?

**Comment by chirsz-ever** [comment]
Good work!

I am a native Chinese speaker. I did some translation works on my local branch in past few months but the process is very slow.

We can reference the translation in [fangcun010/VulkanTutorialCN](https://github.com/fangcun010/VulkanTutorialCN). Maybe I would be able to start this work in the next few weeks.

---
@fangcun010 

虽然 MIT 协议能直接用，但还是请问是否介意直接参考和使用您的译文？有空的话希望能一同进行接下来的工作！

**Comment by fangcun010** [comment]
I'm more than happy to help, you can use whatever you want.

**Comment by fangcun010** [comment]
> Good work!
> 
> I am a native Chinese speaker. I did some translation works on my local branch in past few months but the process is very slow.
> 
> We can reference the translation in [fangcun010/VulkanTutorialCN](https://github.com/fangcun010/VulkanTutorialCN). Maybe I would be able to start this work in the next few weeks.
> 
> @fangcun010
> 
> 虽然 MIT 协议能直接用，但还是请问是否介意直接参考和使用您的译文？有空的话希望能一同进行接下来的工作！

Ok.
I'm more than happy to help, you can use whatever you want.

**Pull request closed without merging**
