### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by QuartzIsCheap**
Hi Alexander,
Here is the tutorial with a French version added. I made sure the translation is up to date with
your latest alterations to the original version.
Feyleth put the English files in an en/ folder, the French files in fr/, and updated the script to generate both French and English pdfs and epubs. As it is the repo is in a usable state.
You would have to update the download links for the pdf/epub versions though.

### CODE REVIEW

**Comment by Overv** [comment]
Very nice work! 👏

I have a test version running at https://dev.vulkan-tutorial.com/.

To support the multiple languages I've updated the CMS to the latest version, however this will require the theme to be ported and some changes to adapt the language handling to my preferences. I will try to get it up and running as soon as possible.

**Comment by QuartzIsCheap** [comment]
Thanks!
I'm glad I could finish it.
Should I close this pr?

**Comment by Overv** [comment]
Not yet, I'll be working on it for a bit to get it production ready.

**Comment by QuartzIsCheap** [comment]
Ok!

**Comment by Overv** [comment]
Your translation is now live at https://vulkan-tutorial.com/! Thanks again for the amazing contribution.

I'm sorry that it took so long but I needed to find the time to overhaul the deployment of the website so I could update to a modern version of the CMS to properly support multilanguage.

**Comment by QuartzIsCheap** [comment]
Great to hear! I took some time too :smirk:
Anyways, glad I could help. I'll try to update the translation from time to times.

**Comment by QuartzIsCheap** [comment]
Great to hear! I took some time too :smirk:
Anyways, glad I could help. I'll try to update the translation from time to times.

**Pull request merged**
