### PR TITLE
Apple M1 Added

### PR DESCRIPTION
**Pull request by rithulkamesh**
Requested edit to add the new SoC by Apple, the Apple Silicon or the m1,

### CODE REVIEW

**Comment by Overv** [comment]
Could you change the casing to "Apple"? Then I'll merge it.

**Comment by rithulkamesh** [comment]
Yep, 1 second

**Comment by rithulkamesh** [comment]
I added it :), is there a discord server btw?

**Comment by Overv** [comment]
Thanks!

>is there a discord server btw?

Do you mean specifically for this tutorial? If so, not that I know of. I don't really use Discord much myself.

**Pull request merged**
