### PR TITLE
Several fixes for french transalation

### PR DESCRIPTION
**Pull request by LittleWhite-tb**
Fixes several typos and easy to spot grammar mistakes
Fixes missing space before newline
Fixes few specific french syntax (i.e. space before ':')

### CODE REVIEW

**Comment by Overv** [comment]
Why did you change the `generateMipmaps` call?

**Comment by LittleWhite-tb** [comment]
My bad. I didn't want to change that, but I messed up with git.

**Comment by Overv** [comment]
Thanks for the quick fix! Thank you very much for taking the time to do this :)

**Comment by LittleWhite-tb** [comment]
No problem ;)

**Pull request merged**
